version: "3.7"

# YAML Anchors

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  SG_ENV: ${SG_ENV:-development}
  TZ: $TZ

x-rethinkdb-client-env: &rethinkdb-client-env
  RETHINKDB_HOST: ${RETHINKDB_HOST:-rethink}
  RETHINKDB_PORT: ${RETHINKDB_PORT:-28015}
  RETHINKDB_DB: ${RETHINKDB_DB:-place_development}

services:
  frontends: # Frontends
    build:
      context: ./
      dockerfile: Dockerfile.test
    hostname: frontends
    volumes:
      - ./spec:/app/spec
      - ./src:/app/src
    depends_on:
      - rethink
    environment:
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION-}
      <<: *deployment-env
      # Service Hosts
      <<: *rethinkdb-client-env

  rethink:
    image: rethinkdb:${RETHINKDB_VERSION:-2.4}
    restart: always
    hostname: rethink
